{
    'name': 'Daily Report',
    'version': '17.0.1.0.0',
    'summary': 'Daily Report',
    'depends': ['base', 'web', 'mail', 'hr','tijus_custom_base'],
    'author': 'Tijus Academy',
    'data': [
        'data/activity.xml',
        'security/group.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'views/job_status_view.xml',
        'views/report_view.xml',
        'views/employee_report_view.xml',
        'views/daily_report_menu.xml',
        'data/job_status_data.xml',
    ],
    'application': True,
    'license': 'LGPL-3',
}
